import './style.scss'
import Cleave from 'cleave.js'
import '../project.blocks/text-field/text-field.js'
import '../project.blocks/header-nav/header-nav.js'
import '../project.blocks/dropdown/dropdown.js'
import '../project.blocks/list-counter/list-counter.js'
import '../project.blocks/date/date.js'
import '../project.blocks/range-slider/range-slider.js'
import '../project.blocks/form-elements/form-elements.js'
import '../project.blocks/number-card/number-card.js'
import '../project.blocks/room-details/room-details.js'
import '../project.blocks/landing-page/landing-page.js'