import './style.scss'
import Cleave from 'cleave.js'
import '../project.blocks/text-field/text-field.js'
import '../project.blocks/dropdown/dropdown.js'
import '../project.blocks/list-counter/list-counter.js'
import '../project.blocks/date/date.js'
import '../project.blocks/range-slider/range-slider.js'
import '../project.blocks/paginator/paginator.js'